### ISSUE TITLE
[PE-D][Tester A] Find Command Not Working As Described

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-3/tp#107]
I tried the command "find ye" as shown in the following picture

![Find Command Not Working Properly Part 1.png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/a0941682-e110-4acd-b88a-49824a42d77c.png)

And the person Alex Yoeh is shown as shown in the following picture

![Find Command Not Working Properly Part 2.png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/c48df231-c129-455d-899d-92390c7a2741.png)

According to the User Guide, only the name is searched for the find Command, shown in the following picture

![Find Command Not Working Properly Part 3.png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/2c4d2a63-cb42-44e5-b1ee-324c112e4a6a.png)

However, Alex Yoeh doesn't have the String 'ye' or any subString 'ye'.

I guess there is a potential bug in the FindCommandPaser, maybe the Parser look for other attributes as well instead of just name.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Yufannnn/ped#2

**Comment by rexcyrio** [comment]
During the PE-D, some peer reviewers got the old version of the UG. This resulted in the features in the app and its described behaviour in the UG differing (see [https://github.com/nus-cs2103-AY2223S2/forum/issues/306](https://github.com/nus-cs2103-AY2223S2/forum/issues/306))

The current UG and current `find` feature are already in sync. Closing this issue as there is nothing to fix.
