### ISSUE TITLE
[PE-D][Tester A] Find Command Seem to be Redundent.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-3/tp#118]
Comparing the documentation of the Find Command and Filter Command, it seems that the functionality of the Find command is covered by Filter by name

![find.png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/a21e1e3f-31ab-4b22-be6a-fe6b601f2739.png)
![filter .png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/5a33ac42-2a54-47aa-898c-f7f8517d0321.png)

Therefore, I suppose maybe the redundant find command can be removed or can enhance to make it less redundant.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Yufannnn/ped#7

**Comment by rexcyrio** [comment]
During the PE-D, some peer reviewers got the old version of the UG. This resulted in the features in the app and its described behaviour in the UG differing (see [https://github.com/nus-cs2103-AY2223S2/forum/issues/306](https://github.com/nus-cs2103-AY2223S2/forum/issues/306))

The current UG and current `find` feature are already in sync. Closing this issue as there is nothing to fix.
