### ISSUE TITLE
[PE-D][Tester A] Long Names are Not Properly Dispalyed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-3/tp#120]
Long Names of persons are cut off by the edges of the window for both the person list and the favorite person list so that I am not able to read the full name of the person.

![Super Long Names not Properly Displayed.png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/e301a127-f868-490b-b11a-d02a16fc1b14.png)

I suppose this can be fixed by making a list horizontally scrollable or limiting the length of the name, or making an auto switch line function so that the name can be properly displayed

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Yufannnn/ped#8

**Comment by minosx31** [comment]
Duplicate issue with #106
