### ISSUE TITLE
[PE-D][Tester D] Find command results don't match inputted names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-3/tp#125]
Inputting a find command `find 9 8 0` shows a list with 6 persons in it despite none of them having the numbers 9, 8 or 0 in their names
![Screenshot 2023-03-31 at 2.42.53 PM.png](https://raw.githubusercontent.com/zrei/ped/main/files/75a6f250-059d-423a-81af-c09df1bdd576.png)
![Screenshot 2023-03-31 at 2.42.59 PM.png](https://raw.githubusercontent.com/zrei/ped/main/files/139b44b6-348e-49a0-a87a-b3bc9e67a7a2.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: zrei/ped#4

**Comment by rexcyrio** [comment]
During the PE-D, some peer reviewers got the old version of the UG. This resulted in the features in the app and its described behaviour in the UG differing (see [https://github.com/nus-cs2103-AY2223S2/forum/issues/306](https://github.com/nus-cs2103-AY2223S2/forum/issues/306))

The current UG and current `find` feature are already in sync. Closing this issue as there is nothing to fix.
